### ISSUE TITLE
Include position in match results

### ISSUE THREAD

**Issue by nathanielknight** [gleam-lang/regexp#1]
First of all, thank you for all of your hard work on Gleam and on the Gleam community. It's a not-irregular occurrence for me to mutter "damn, these Gleam folks are really killing it" to myself, so well done!

This is more of an enhancement request, than an issue per-se, but I think it would be super helpful to **include position information** in the `Match` object returned by `scan`.

My use case in particular was building a parser for an Advent of Code problem; I needed to find part of a line of text that was formatted as an integer, including where it is. Obviously that's not super practical, but hopefully it illustrates the point.

Glancing at the underlying Erlang and JavaScript libraries it looks like they do support position info with UTF-8 support (so I'd expect it to work in terms of graphemes, which is how I think Gleam would want it to work).

If this addition would be useful I could try to implement it, but I don't want to waste everyone's time with patches that only I want 😅

**Comment by lpil** [comment]
Sounds useful to me!

**Comment by nathanielknight** [comment]
Hmmmmm, so not as easy as I'd hoped 😅 

As noted [in the docs](https://www.erlang.org/doc/apps/stdlib/re.html#:~:text=Notice%20that%20option%20unicode%20results%20in%20byte-oriented%20indexes), Erlang's regexp module returns byte-based indexes, and even the NodeJS modules doesn't handle all the test cases gracefully (here's a [branch](https://github.com/nathanielknight/regexp/tree/WIP-add-position) to show what I mean).

**Comment by nathanielknight** [comment]
So, some possible solutions after thinking on this for a bit:

* For the JavaScript target, I think it probably makes the most sense to return whatever the underling engine does (regexes are [in the ECMAScript spec](https://tc39.es/ecma262/multipage/text-processing.html#sec-regexp-regular-expression-objects), so leaning on the platform quirks-and-all seems like the right thing to do).

* For the Erlang target there are a few options:
  * Return byte-based indices with a giant caveat.
  * Use some combination of `string.to_graphemes` and `string.byte_size` to figure out what the grapheme index of a particular byte is. This seems tricky, and possibly very slow.
  * Replace Erlang's `re` with a NIF that calls something like PCRE2 (which I _believe_ is the regex engine that `ripgrep` uses, and it handles the indices the way I'd expect). This seems differently tricky, but Erlang's `re` module [uses PCRE already](https://www.erlang.org/doc/apps/stdlib/re.html#:~:text=The%20matching%20algorithms%20of%20the%20library%20are%20based%20on%20the%20PCRE%20library), so creating a new NIF shouldn't change the performance or safety characteristics _too_ much.

Any feedback on direction would be greatly appreciated. 😟

**Comment by lpil** [comment]
Options 2 and 3 don't sound viable to me.

Could you expand on the first one please? What would returning byte indexes look like?

**Comment by nathanielknight** [comment]
In my testing I added a `start_position` field to `regexp.Match`:

```gleam
/// The details about a particular match:
///
pub type Match {
  Match(
    /// The full string of the match.
    content: String,
    /// A `Regexp` can have subpatterns, sup-parts that are in parentheses.
    submatches: List(Option(String)),
    /// TODO docs
    start_position: Int,
  )
}
```

Adapting some code from the unit tests:

```gleam
fn check(input: String) {
    let assert Ok(re) = regexp.from_string("Gl\\w+")
    regexp.scan(re, input)
}

[ "!Gleam", "हGleam", "𐍈Gleam" ] |> list.map(check)
```

I get the following:



| Input | Special Character | Special Character Byte Size | Erlang Result | JS Result |
| ----- | ------------- | --- | --- | --------- |
| `"!Gleam"` | `!` Exclamation Mark (U+0021) | 1 | `[Match("Gleam", [], 1)]` | `[Match("Gleam", [], 1)]` |
| `"हGleam"` | `ह` Devanagari Letter Ha (U+0939) | 3 | `[Match("Gleam", [], 3)]"` | `[Match("Gleam", [], 1)]` |
| `"𐍈Gleam"` | `𐍈` Gothic Letter Hwair (U+10348) | 4|  `[Match("Gleam", [], 4)]` | `[Match("Gleam", [], 2)]` |

As you can see:

* Both targets handle the ASCII case the way we'd hope. 🎉
* The JavaScript runtime handles the Letter Ha as we'd hope (with a character-based index) but the Erlang target counts bytes instead of letters.
* Erlang handles Letter Hwair _consistently_, even if it's bytes-based; I'm not sure what the JavaScript runtime is doing here...

**Comment by lpil** [comment]
Sorry, I'm not understanding. I am having a slow day! Why would we want it to have a byte index? What could the programmer do with that information?

**Comment by nathanielknight** [comment]
* It’s the only information that’s available on the Erlang target (I was mistaken about that).
* If you needed to, and you knew the input would be small or regular enough, you could split the string into graphemes, count the bytes in each grapheme, and scan through that list until you got to the match.

**Comment by lpil** [comment]
We don't add information just because it's present, changes are motivated by real-world needs. Would you use this in your application? Could you share more on that please? 🙏

**Comment by nathanielknight** [comment]
So I was prompted to look while writing a parser for Advent of Code: I needed the position of particular characters within a problem input. I ended up manually writing a recursive parser instead (which was pretty easy, since AoC is constructed to be fun to solve).

> We don't add information just because it's present,

With this (laudable) ethos in mind, I think it's probably best to drop this for now.

Thanks for your input, and thanks again for all your hard work on Gleam!
